<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [36]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [11]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [12]:
%%sql

SELECT * FROM SALES LIMIT 50

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

50 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16
10,1004,2,2015-01-01,2015-01-01,254117,80,1633,1,8.33,8.33,3.83,CAD,1.16
11,1004,3,2015-01-01,2015-01-01,254117,80,450,1,2297.50,2067.75,761.20,CAD,1.16
12,1005,0,2015-01-01,2015-01-01,1160597,390,1303,10,152.00,152.00,69.90,GBP,0.64
13,1005,1,2015-01-01,2015-01-01,1160597,390,1705,2,4.82,4.82,2.21,GBP,0.64
14,1006,0,2015-01-01,2015-01-01,1895118,480,173,1,71.92,63.29,36.66,USD,1.00
15,1006,1,2015-01-01,2015-01-01,1895118,480,998,5,316.80,310.46,145.68,USD,1.00
16,1007,0,2015-01-01,2015-01-01,1008672,410,55,1,222.00,222.00,73.55,GBP,0.64
17,1007,1,2015-01-01,2015-01-01,1008672,410,1692,4,4.89,4.45,2.49,GBP,0.64
18,1007,2,2015-01-01,2015-01-01,1008672,410,95,1,50.55,50.04,25.77,GBP,0.64
19,1007,3,2015-01-01,2015-01-01,1008672,410,53,1,222.00,222.00,73.55,GBP,0.64
20,1007,4,2015-01-01,2015-01-01,1008672,410,1575,3,36.59,35.13,16.83,GBP,0.64
21,1007,5,2015-01-01,2015-01-01,1008672,410,1816,3,22.40,19.49,11.42,GBP,0.64
22,1008,0,2015-01-01,2015-01-01,1576121,530,574,1,272.50,247.97,138.93,USD,1.00
23,1008,1,2015-01-01,2015-01-01,1576121,530,2166,2,333.75,287.02,153.48,USD,1.00
24,1008,2,2015-01-01,2015-01-01,1576121,530,1581,2,131.40,131.40,43.54,USD,1.00
25,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
26,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
27,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
28,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
29,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
30,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
31,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
32,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
33,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
34,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00
35,3001,0,2015-01-03,2015-01-03,1048105,400,1653,3,65.99,60.71,33.65,GBP,0.65
36,3002,0,2015-01-03,2015-01-03,1035492,390,143,2,239.99,211.19,122.35,GBP,0.65
37,3002,1,2015-01-03,2015-01-03,1035492,390,2098,1,381.00,327.66,194.24,GBP,0.65
38,3002,2,2015-01-03,2015-01-03,1035492,390,130,1,160.00,139.20,81.58,GBP,0.65
39,3003,0,2015-01-03,2015-01-03,787164,290,1164,1,288.00,288.00,146.83,EUR,0.83
40,3004,0,2015-01-03,2015-01-03,758284,290,681,1,302.50,302.50,139.10,EUR,0.83
41,3005,0,2015-01-03,2015-01-03,1265697,570,109,3,99.74,99.74,45.87,USD,1.00
42,3005,1,2015-01-03,2015-01-03,1265697,570,327,2,223.20,196.42,113.79,USD,1.00
43,3006,0,2015-01-03,2015-01-03,2003801,550,1874,2,1363.50,1199.88,627.02,USD,1.00
44,3007,0,2015-01-03,2015-01-03,741423,280,1642,3,34.73,34.73,15.97,EUR,0.83
45,3007,1,2015-01-03,2015-01-03,741423,280,1591,4,7.60,6.91,3.49,EUR,0.83
46,3008,0,2015-01-03,2015-01-03,1614670,530,61,4,135.75,135.75,62.43,USD,1.00
47,3008,1,2015-01-03,2015-01-03,1614670,530,181,6,103.20,93.91,47.46,USD,1.00
48,3009,0,2015-01-03,2015-01-11,208950,999999,2163,2,97.42,91.58,49.67,CAD,1.17
49,3009,1,2015-01-03,2015-01-11,208950,999999,553,4,1747.50,1747.50,803.60,CAD,1.17

In [20]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [25]:
%%sql

SELECT * FROM information_schema.columns WHERE table_name = 'customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [26]:
%%sql

SELECT * FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [29]:
%%sql

SELECT *, quantity * netprice * exchangerate as net_revenue FROM sales limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate,net_revenue
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64,63.49
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64,423.28
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00,108.75
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00,1146.75
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00,950.25
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00,1302.91
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00,58.73
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00,224.98
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16,263.11
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16,578.52

In [3]:
%%sql

SELECT orderdate, quantity * netprice * exchangerate AS net_revenue FROM sales WHERE orderdate::date >= '2020-01-10'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

123666 rows affected.

         orderdate  net_revenue
0       2020-01-10        25.97
1       2020-01-10       109.96
2       2020-01-10       688.44
3       2020-01-10        26.05
4       2020-01-10        12.69
...            ...          ...
123661  2024-04-20       914.61
123662  2024-04-20       150.18
123663  2024-04-20       147.78
123664  2024-04-20      2019.62
123665  2024-04-20        56.83

[123666 rows x 2 columns]

In [10]:
%%sql

SELECT s.orderdate, s.quantity * s.netprice * s.exchangerate AS net_revenue
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE orderdate::date >= '2024-01-01'
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2024-01-01         6.28
1  2024-01-01        82.56
2  2024-01-01       307.26
3  2024-01-01       777.00
4  2024-01-01        98.52
5  2024-01-01      3582.34
6  2024-01-01      1451.33
7  2024-01-01        11.14
8  2024-01-01       380.38
9  2024-01-01        13.89

In [15]:
%%sql

SELECT orderdate, s.quantity * s.netprice * exchangerate AS net_revenue, c.givenname, c.surname, c.countryfull, c.continent
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE orderdate::date >= '2024-01-01'
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue givenname    surname    countryfull      continent
0  2024-01-01         6.28   Leonard     Grimes         Canada  North America
1  2024-01-01        82.56  Jennifer       Webb  United States  North America
2  2024-01-01       307.26    Robert      Young  United States  North America
3  2024-01-01       777.00    Robert      Young  United States  North America
4  2024-01-01        98.52     Steve   Anderson         Canada  North America
5  2024-01-01      3582.34     Steve   Anderson         Canada  North America
6  2024-01-01      1451.33     Marie    Faerber        Germany         Europe
7  2024-01-01        11.14     Diego  Rodrigues  United States  North America
8  2024-01-01       380.38     Diego  Rodrigues  United States  North America
9  2024-01-01        13.89    Cheryl       Rios  United States  North America

In [16]:
%%sql

SELECT orderdate, s.quantity * s.netprice * exchangerate AS net_revenue, c.givenname, c.surname, c.countryfull, c.continent
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productKey = p.productKey
WHERE orderdate::date >= '2024-01-01'
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue givenname    surname    countryfull      continent
0  2024-01-01         6.28   Leonard     Grimes         Canada  North America
1  2024-01-01        82.56  Jennifer       Webb  United States  North America
2  2024-01-01       307.26    Robert      Young  United States  North America
3  2024-01-01       777.00    Robert      Young  United States  North America
4  2024-01-01        98.52     Steve   Anderson         Canada  North America
5  2024-01-01      3582.34     Steve   Anderson         Canada  North America
6  2024-01-01      1451.33     Marie    Faerber        Germany         Europe
7  2024-01-01        11.14     Diego  Rodrigues  United States  North America
8  2024-01-01       380.38     Diego  Rodrigues  United States  North America
9  2024-01-01        13.89    Cheryl       Rios  United States  North America

In [25]:
%%sql

SELECT orderdate, s.quantity * s.netprice * exchangerate AS net_revenue,
c.givenname,
c.surname,
c.countryfull,
c.continent,
p.productkey,
p.productname,
p.categoryname,
p.subcategoryname,
CASE WHEN s.quantity * s.netprice * exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS high_low
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productKey = p.productKey
WHERE orderdate::date >= '2024-01-01'
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2024-01-01,6.28,Leonard,Grimes,Canada,North America,2506,Contoso Rubberized Snap-On Cover Hard Case Cel...,Cell phones,Cell phones Accessories,LOW
1,2024-01-01,82.56,Jennifer,Webb,United States,North America,1775,MGS Shadow-run 2008 E131,Games and Toys,Download Games,LOW
2,2024-01-01,307.26,Robert,Young,United States,North America,190,SV 8xDVD E130 Silver,TV and Video,VCD & DVD,LOW
3,2024-01-01,777.00,Robert,Young,United States,North America,312,SV Car Video TFT6.2W E6281 Silver,TV and Video,Car Video,LOW
4,2024-01-01,98.52,Steve,Anderson,Canada,North America,2332,Litware Desk Lamp E1030 Silver,Home Appliances,Lamps,LOW
5,2024-01-01,3582.34,Steve,Anderson,Canada,North America,416,Adventure Works Desktop PC2.33 XD233 Silver,Computers,Desktops,HIGH
6,2024-01-01,1451.33,Marie,Faerber,Germany,Europe,1657,Contoso DVD 12-Inch Player Portable M400 White,"Music, Movies and Audio Books",Movie DVD,HIGH
7,2024-01-01,11.14,Diego,Rodrigues,United States,North America,1636,Contoso DVD 55DVD Storage Binder M56 Silver,"Music, Movies and Audio Books",Movie DVD,LOW
8,2024-01-01,380.38,Diego,Rodrigues,United States,North America,658,Proseware High Speed Laser M2000 Black,Computers,"Printers, Scanners & Fax",LOW
9,2024-01-01,13.89,Cheryl,Rios,United States,North America,1588,SV DVD 58 DVD Storage Binder M55 Silver,"Music, Movies and Audio Books",Movie DVD,LOW

In [29]:
%%sql

SELECT orderdate, customerKey FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  customerkey
0       2015-01-01       947009
1       2015-01-01       947009
2       2015-01-01      1772036
3       2015-01-01      1518349
4       2015-01-01      1518349
...            ...          ...
199868  2024-04-20       664396
199869  2024-04-20       664396
199870  2024-04-20       267690
199871  2024-04-20       267690
199872  2024-04-20       267690

[199873 rows x 2 columns]

In [33]:
%%sql

SELECT orderdate, COUNT(customerKey) AS total_customers FROM sales GROUP BY orderdate ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  total_customers
0     2015-01-01               25
1     2015-01-02                8
2     2015-01-03               21
3     2015-01-05               10
4     2015-01-06               12
...          ...              ...
3289  2024-04-16               32
3290  2024-04-17               61
3291  2024-04-18               57
3292  2024-04-19               50
3293  2024-04-20               97

[3294 rows x 2 columns]

In [35]:
%%sql

SELECT orderdate, COUNT(DISTINCT customerKey) AS total_customers FROM sales WHERE orderdate BETWEEN '2020-01-01' AND '2024-01-01'GROUP BY orderdate ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1424 rows affected.

       orderdate  total_customers
0     2020-01-01               46
1     2020-01-02               52
2     2020-01-03               34
3     2020-01-04               62
4     2020-01-05                5
...          ...              ...
1419  2023-12-28               75
1420  2023-12-29               55
1421  2023-12-30               91
1422  2023-12-31                9
1423  2024-01-01               40

[1424 rows x 2 columns]

In [42]:
%%sql

SELECT orderdate, COUNT(DISTINCT s.customerKey) AS total_customer
FROM sales s
LEFT JOIN customer c ON c.customerKey = s.customerKey
WHERE orderdate BETWEEN '2020-01-01' AND '2024-01-01'
GROUP BY orderdate ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1424 rows affected.

       orderdate  total_customer
0     2020-01-01              46
1     2020-01-02              52
2     2020-01-03              34
3     2020-01-04              62
4     2020-01-05               5
...          ...             ...
1419  2023-12-28              75
1420  2023-12-29              55
1421  2023-12-30              91
1422  2023-12-31               9
1423  2024-01-01              40

[1424 rows x 2 columns]

In [53]:
%%sql

SELECT orderdate,
COUNT(DISTINCT s.customerKey) AS total_customer,
COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerKey END) AS eu_customer
FROM
sales s
LEFT JOIN customer c ON s.customerKey = c.customerKey
WHERE orderdate BETWEEN '2020-01-01' AND '2024-01-01'
GROUP BY orderdate
ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1424 rows affected.

       orderdate  total_customer
0     2020-01-01              46
1     2020-01-02              52
2     2020-01-03              34
3     2020-01-04              62
4     2020-01-05               5
...          ...             ...
1419  2023-12-28              75
1420  2023-12-29              55
1421  2023-12-30              91
1422  2023-12-31               9
1423  2024-01-01              40

[1424 rows x 2 columns]